server:
  port: '8080'
spring:
  data:
    mongodb:
      authentication-database: admin
      username: UserTest
      database: MyTestDB
      password: UserTest123*
      port: '27017'
      host: localhost